name: Commit created file

on: 
  push:
    paths:
      - 'docs/guide/en/**'
      - 'docs/guide/test/**'

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name:  Create test.txt
        run: |
          ls -al
          touch test.txt
          ls -al
      
      - name: Commit file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'test.txt'
          message: 'Added test.txt'
          push: true

      - name: install po4a
        run: |
          sudo apt -q update
          sudo apt install -qy build-essential
          sudo apt install -qy gettext liblocale-gettext-perl xsltproc
          sudo cpan -T install Module::Build
          sudo cpan -T install Locale::gettext
          sudo cpan -T install Unicode::GCString
          sudo cpan -T install Text::WrapI18N
          sudo cpan -T install Term::ReadKey
          sudo cpan -T install YAML::Tiny
          sudo cpan -T install Syntax::Keyword::Try
          git clone https://github.com/mquinson/po4a.git
          cd po4a && perl Build.PL
          cd po4a && ./Build; exit 0
          cd po4a && ./Build install
          po4a --version