name: Commit created file

on: 
  push:
    paths:
      - 'docs/guide/en/**'
      - 'docs/guide/test/**'

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name:  Create test.txt
        run: |
          ls -al
          touch test.txt
          ls -al
      
      - name: Commit file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'test.txt'
          message: 'Added test.txt'
          push: true

      - name: install po4a
        run: |
          apt-get -q update
          apt-get -qy upgrade
          apt-get install -qy build-essential