name: Update docs translation

on:
  push:

jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token || github.token }}
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Use po4a
        uses: addnab/docker-run-action@v3
        with:
            image: arduanovdanil/po4a-fork:latest
            options: -v ${{ github.workspace }}:/var/www
            run: |
                ls -al