name: Update docs translation

on:
  push:

jobs:
jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    container: arduanovdanil/po4a-fork:latest  # Контейнер как среда
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token || github.token }}
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Use container
        run: |
          ls -al /github/workspace/docs  # Проверка файлов
          po4a --version  # Теперь доступно