name: Update docs translation

on:
  push:

jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token || github.token }}
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Use po4a
        uses: addnab/docker-run-action@v3
        with:
            image: arduanovdanil/po4a-fork:latest
            options: -v ${{ github.workspace }}:/src
            run: |
                cd docs
                po4a --version
                po4a po4a.cfg

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update docs translation
          file_pattern: 'docs'