name: Commit created file

on: 
  push:
    paths:
      - 'docs/guide/en/**'
      - 'docs/guide/test/**'

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name:  Create test.txt
        run: |
          ls -al
          touch test.txt
          ls -al
      
      - name: Commit file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'test.txt'
          message: 'Added test.txt'
          push: true

      - name: Install Debian dependencies
        run: |
          sudo apt update 
          sudo apt install -y liblocale-gettext-perl libtext-wrapi18n-perl libunicode-linebreak-perl libpod-parser-perl libtest-pod-perl libyaml-tiny-perl libsyntax-keyword-try-perl
          sudo apt install -y cpanminus gettext docbook-xml docbook-xsl docbook xsltproc
          sudo apt install -y texlive-binaries texlive-latex-base opensp libsgmls-perl
      - name: Install CPAN dependencies
        run: |
          cpanm Locale::gettext
          cpanm http://search.cpan.org/CPAN/authors/id/R/RA/RAAB/SGMLSpm-1.1.tar.gz
          cpanm Text::WrapI18N
          cpanm Unicode::GCString
          cpanm -v --installdeps --notest .
        
      - name: Clone po4a
        run: |
          git clone https://github.com/mquinson/po4a.git

      - name: Build po4a
        run: |
          cd po4a
          ls -al
