name: Update docs translation

on:
  push:

jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    container: arduanovdanil/po4a-fork:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          clean: false

      - name: Run in container
        run: |
          po4a --version
          ls -al
          echo This job does specify a container.
          echo It runs in the container instead of the VM.