name: Update docs translation

on:
  push:

jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src

      - name: Run in container
        run: |
          pwd
          ls -al