name: Update docs translation

on:
  push:

jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    services:
      po4a:
        image: arduanovdanil/po4a-fork:latest
        volumes:
          - docs:/docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token || github.token }}
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Use container
        run: |
          ls -al