name: Commit created file

on: 
  pull_request:
    types: [opened]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name:  Create test.txt
        run: |
          ls -al
          touch test_file.txt
          ls -al
      
      - name: Commit file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'test.txt'
          message: 'Added test.txt'
          push: true
